# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Express...
      - npm install -g express
    commands:
      - echo Installing Nodemon...
      - npm install -g nodemon
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --only=prod -y -g --unsafe-perm
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
    - '**/*'